name: 檢查拉取請求

on:
  push:
    branches-ignore:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 確保拉取完整 commit 歷史

      - name: Run Commitlint
        uses: ahmadnassri/action-commit-lint@v2
        with:
          config: conventional
          token: ${{ secrets.GITHUB_TOKEN }}
