name: PR Workflow
on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run your tests
        run: echo "Testing pull request"
